# Generated by Django 6.0.5 on 2026-06-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_directmessage'),
        ('manager', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='manager.profile'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='manager.profile'),
        ),
    ]
