# Generated by Django 6.0.5 on 2026-06-03 23:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_merge_0006_merge_20260506_1056_0007_anime_dislikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='El año no puede ser anterior a 1900'), django.core.validators.MaxValueValidator(2031, message='El año no puede ser tan futuro')])),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('background_image', models.URLField(blank=True, max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='La calificación no puede ser negativa'), django.core.validators.MaxValueValidator(10.0, message='La calificación no puede ser mayor a 10.0')])),
                ('chapter_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('manga_slug', models.CharField(blank=True, help_text='Slug identificador del manga', max_length=255)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dislikes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
